### ISSUE TITLE
nodeMix not available in directed network

### ISSUE THREAD

**Issue by manuelhopp** [statnet/lolog#7]
I'm using R v4.3.2 and lolog v1.3.1. As data I use a directed friendship network.
When I run the estimation with "nodeMix" included, I received the following error message:

> Error in .makeCppModelFromTerms(terms, net, theta, modelClass) :
> Error in model$addStatistic(names(stats)[i], stats[[i]]) :
> Unknown statistic: nodeMix

Other effects, such as nodeCov work flawlessly. 

Code to reproduce the error:
```R
library(lolog)
suppressPackageStartupMessages(library(ergm))
data(samplk)

lolog(samplk1 ~ edges() + 
        mutual() + 
        triangles() + 
        nodeMix("cloisterville"))
```

**Comment by handcock** [comment]
I think it is because `nodeMix` in `lolog` currently only supports undirected networks. For example,

```library(lolog)
suppressPackageStartupMessages(library(ergm))
data(florentine)
fnet <- as.BinaryNet(flomarriage)
fnet$variableNames()
# Create a discrete version of priorates
fnet[["priorates_cat"]] <- cut(flomarriage %v% "priorates",2)
fnet$variableNames()
# Fit, but edges() not needed
lolog(fnet ~  triangles() + 
        nodeMix("priorates_cat"))
```

It would be easy to add.

**Comment by ifellows** [comment]
Mark is correct. I believe it is just that it isn't exported in StatController.cpp. I've assigned myself the task.

**Comment by ifellows** [comment]
NodeMix has now been added for directed networks. @mds-hopp , install the package from github and the stat should be available.
