### ISSUE TITLE
Compatibility with igraph 2.0.0

### ISSUE THREAD

**Issue by krlmlr** [statnet/lolog#8]
@ifellows @handcock: This package does not terminate its checks when run with the release candidate for igraph 2.0.0.

Is this a problem in your package? Should we be doing things differently?

Install the 2.0.0 release candidate using `pak::pak("igraph/rigraph")` .

We're planning to release igraph 2.0.0 on January 23. My sincere apologies for the short notice, I only realized today that I should have warned about the problem much earlier. Happy to postpone if it turns out that the problem is on our end. Thank you for your help!

Tracker: https://github.com/igraph/rigraph/issues/989.

**Comment by krlmlr** [comment]
Installing from r-universe might be easier: https://igraph.r-universe.dev/igraph# .

**Comment by ifellows** [comment]
@krlmlr lolog only uses igraph through intergraph. The only time it is called directly is in the tests to check the intergraph conversions by calling 
```
g <- igraph::make_full_graph(5)
```
Could it be that the problem lies upstream in either intergraph or igraph?

**Comment by krlmlr** [comment]
Can you please test with the dev version of intergraph?

CC @mbojan.

**Comment by ifellows** [comment]
@krlmlr can you please provide steps to reproduce the error you see with your updated package, including install steps for any non-cran package code.

**Comment by krlmlr** [comment]
We did roughly the following:

- Install the development version from igraph, perhaps easiest from https://igraph.r-universe.dev/igraph#
- Run `R CMD check` with lolog

The check did not terminate.

Install the dev version of intergraph with `pak::pak("mbojan/intergraph")` or `remotes::install_github("mbojan/intergraph")` .

**Comment by ifellows** [comment]
I have followed those steps and everything checks out okay. Note the vignettes take a very long time to compile for this package, so perhaps that is what you were running into. Cran uses --no-vignettes when checking `lolog`. Please try again with that flag and let me know if any issues persist.
